//! Reading a dump: the hierarchy, the values, and what happens at the edges.
//!
//! VCD is a text format, so the fixtures here are written by hand rather than
//! produced by a simulator. That keeps the tests fast and, more usefully, lets
//! them contain the cases a real dump rarely has on demand — an `x` region, a
//! variable aliased under two names, a value read before the first change.

use rtlscope_wave::Dump;

/// A dump with two scopes, a clock, a bus, an aliased signal and an `x` region.
fn basic() -> Dump {
    let text = "\
$date Sat Aug 30 2026 $end
$version handwritten $end
$timescale 1ns $end
$scope module tb $end
$var wire 1 ! clk $end
$scope module dut $end
$var wire 1 ! clk $end
$var wire 8 # data $end
$var wire 1 $ flag $end
$upscope $end
$upscope $end
$enddefinitions $end
#0
0!
bxxxxxxxx #
0$
#5
1!
b00001010 #
1$
#10
0!
#15
1!
b11111111 #
0$
#20
0!
";
    Dump::open_vcd_bytes(text.as_bytes().to_vec()).expect("the fixture parses")
}

#[test]
fn the_hierarchy_comes_back_as_dotted_paths() {
    let dump = basic();
    let mut paths: Vec<&str> = dump.vars().map(|(name, _)| name).collect();
    paths.sort_unstable();
    assert_eq!(paths, ["tb.clk", "tb.dut.clk", "tb.dut.data", "tb.dut.flag"]);

    let data = dump.find("tb.dut.data").expect("the bus");
    assert_eq!(dump.width(data), Some(8));
    assert_eq!(dump.width(dump.find("tb.dut.flag").unwrap()), Some(1));
    assert_eq!(dump.timescale(), Some((1, "ns")));
    assert_eq!(dump.max_time(), 20);
}

#[test]
fn values_come_back_in_time_order() {
    let mut dump = basic();
    let data = dump.find("tb.dut.data").unwrap();
    dump.load(&[data]).expect("loads");

    let changes: Vec<(u64, String)> =
        dump.changes(data).unwrap().map(|(t, v)| (t, v.bit_string())).collect();
    assert_eq!(
        changes,
        [(0, "xxxxxxxx".to_string()), (5, "00001010".to_string()), (15, "11111111".to_string()),]
    );
}

/// The rule that matters most: a value with an `x` in it is never a number.
#[test]
fn an_undriven_value_is_reported_rather_than_read_as_zero() {
    let mut dump = basic();
    let data = dump.find("tb.dut.data").unwrap();
    dump.load(&[data]).unwrap();

    let at_zero = dump.value_at(data, 0).unwrap().expect("a value at time 0");
    assert!(at_zero.is_unknown(), "{at_zero:?}");
    assert_eq!(at_zero.as_u64(), None);

    let settled = dump.value_at(data, 7).unwrap().expect("a value at time 7");
    assert_eq!(settled.as_u64(), Some(10), "the change at 5 still holds at 7");
}

#[test]
fn a_signal_recorded_under_two_names_is_one_signal() {
    let mut dump = basic();
    let outer = dump.find("tb.clk").unwrap();
    let inner = dump.find("tb.dut.clk").unwrap();

    // Loading one loads the other: they share an identifier in the file.
    dump.load(&[outer]).unwrap();
    let outer_changes: Vec<u64> = dump.changes(outer).unwrap().map(|(t, _)| t).collect();
    let inner_changes: Vec<u64> = dump.changes(inner).unwrap().map(|(t, _)| t).collect();
    assert_eq!(outer_changes, [0, 5, 10, 15, 20]);
    assert_eq!(inner_changes, outer_changes);
}

#[test]
fn asking_for_a_signal_that_was_never_loaded_says_so() {
    let dump = basic();
    let flag = dump.find("tb.dut.flag").unwrap();
    let error = dump.changes(flag).err().expect("an error rather than empty values");
    assert!(error.to_string().contains("tb.dut.flag"), "{error}");
}

#[test]
fn a_value_before_the_first_change_is_absent_rather_than_invented() {
    let text = "\
$timescale 1ns $end
$scope module tb $end
$var wire 4 ! late $end
$upscope $end
$enddefinitions $end
#100
b0001 !
";
    let mut dump = Dump::open_vcd_bytes(text.as_bytes().to_vec()).unwrap();
    let late = dump.find("tb.late").unwrap();
    dump.load(&[late]).unwrap();
    assert_eq!(dump.value_at(late, 50).unwrap(), None);
    assert_eq!(dump.value_at(late, 100).unwrap().and_then(|v| v.as_u64()), Some(1));
}

/// The real thing: an FST written by Icarus through cocotb, if one is around.
#[test]
fn an_fst_from_a_simulator_reads_the_same_way() {
    let fst = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/counter.fst");
    if !fst.exists() {
        // Generated by the cocotb tests; absent on a checkout that has not run
        // them, and skipping beats a failure that says nothing about the code.
        eprintln!("skipping: no {} to read", fst.display());
        return;
    }
    let mut dump = Dump::open(&fst).expect("the FST opens");
    let names: Vec<&str> = dump.vars().map(|(name, _)| name).collect();
    assert!(!names.is_empty(), "an FST with no variables in it");

    let count = names
        .iter()
        .find(|name| name.ends_with(".count"))
        .and_then(|name| dump.find(name))
        .expect("a `count` variable");
    dump.load(&[count]).unwrap();
    let changes: Vec<u64> =
        dump.changes(count).unwrap().map(|(_, v)| v.as_u64().unwrap()).collect();
    assert!(changes.len() > 2, "{changes:?}");
}
