//! A plain SystemVerilog testbench, for when cocotb is not to hand.
//!
//! cocotb is the better harness — stimulus in Python is easier to write and to
//! change than stimulus in an `initial` block — but it needs a Python with
//! cocotb installed, and a checkout that has only a simulator should still be
//! able to produce a waveform. So this writes the same plan as a self-contained
//! `.sv` file plus a script to compile and run it.
//!
//! The generated file is deliberately dull: clocks, a reset, the design
//! instantiated with every port connected by name, and `$dumpvars`. Everything
//! else is a comment saying where the stimulus goes.

use std::fmt::Write as _;

use rtlscope_ir::{Design, ModuleId, PortDir};

use crate::clocks::{ClockPlan, plan};
use crate::cocotb::{Generated, Stimulus, TbError, TbOptions};

pub fn generate(
    design: &Design,
    module_id: ModuleId,
    options: &TbOptions,
) -> Result<Generated, TbError> {
    let module = &design.modules[module_id];
    if module.is_blackbox {
        return Err(TbError::Blackbox(module.name.clone()));
    }
    for (name, _) in &options.overrides {
        if !module.params.iter().any(|p| &p.name == name && !p.is_local) {
            return Err(TbError::NoSuchParameter(name.clone()));
        }
    }

    let mut plan = plan(design, module_id);
    for (port, period) in &options.periods {
        match plan.clocks.iter_mut().find(|c| &c.port == port) {
            Some(clock) => clock.period_ns = *period,
            None => plan.notes.push(format!("`{port}` is not a clock of this module")),
        }
    }

    // The plan's note says the spare inputs are tied off, which stops being
    // true the moment they are driven. A note that describes the harness that
    // was *not* written is worse than no note.
    if let Stimulus::Random { seed } = options.stimulus
        && !plan.tied_off.is_empty()
    {
        let count = plan.tied_off.len();
        let named = plan.tied_off.join(", ");
        plan.notes.retain(|note| !note.contains("tied off"));
        plan.notes.push(format!(
            "{count} input(s) are neither clock nor reset and are driven at random from seed              {seed}: {named}. This knows no protocol — it makes a waveform, not a verdict."
        ));
    }

    // A drawing is data a player reads, and this harness cannot read one:
    // baking the values in would mean rebuilding the design for every cell
    // repainted, which is the whole reason the pattern is data. cocotb reads
    // it. See `crate::pattern`.
    if matches!(options.stimulus, Stimulus::Drawn(_)) {
        return Err(TbError::DrawnIsCocotbOnly);
    }

    let top = module.base_name.clone();
    let files = vec![
        (format!("tb_{top}.sv"), testbench(design, module_id, &plan, options)),
        ("files.f".to_string(), file_list(options)),
        ("run.ps1".to_string(), script(&top)),
    ];
    Ok(Generated { files, notes: plan.notes.clone() })
}

fn testbench(
    design: &Design,
    module_id: ModuleId,
    plan: &ClockPlan,
    options: &TbOptions,
) -> String {
    let module = &design.modules[module_id];
    let top = &module.base_name;
    let mut out = String::new();

    // Without this Icarus runs at one-second precision, and a nanosecond clock
    // cannot be represented at all.
    out.push_str("`timescale 1ns / 1ps\n\n");
    let _ = writeln!(out, "// Generated by `rtlscope tb-init --flavor sv` for `{top}`.");
    out.push_str("//\n");
    out.push_str("// The clocks and the reset were read out of the design rather than guessed\n");
    out.push_str("// from port names. Every other input is tied off and marked; that is where\n");
    out.push_str("// your stimulus goes.\n\n");
    let _ = writeln!(out, "module tb_{top} ();\n");

    // Declarations: a reg for every input, a wire for every output.
    for port in &module.ports {
        let net = module.net(port.net);
        let range = if net.width > 1 { format!("[{}:0] ", net.width - 1) } else { String::new() };
        let kind = if port.dir == PortDir::Input { "logic" } else { "wire " };
        let _ = writeln!(out, "    {kind} {range}{};", port.name);
    }
    out.push('\n');

    // Set when the reset sequence finishes, so random driving starts against a
    // design that is out of reset rather than during it.
    let driving = matches!(options.stimulus, Stimulus::Random { .. }) && !plan.tied_off.is_empty();
    if driving {
        out.push_str("    logic rtlscope_running = 1'b0;\n\n");
    }

    for clock in &plan.clocks {
        let half = clock.period_ns as f64 / 2.0;
        let _ = writeln!(out, "    // {} flop(s) run on this.", clock.flops);
        let _ = writeln!(out, "    initial {} = 1'b0;", clock.port);
        let _ = writeln!(out, "    always #{half} {} = ~{};", clock.port, clock.port);
    }
    if !plan.clocks.is_empty() {
        out.push('\n');
    }

    // Everything that is neither clock nor reset starts defined, so the design
    // is not driven by `x` from the first edge.
    if !plan.tied_off.is_empty() {
        out.push_str("    // Tied off so nothing starts undriven.\n");
        out.push_str("    initial begin\n");
        for port in &plan.tied_off {
            let _ = writeln!(out, "        {port} = '0;");
        }
        out.push_str("    end\n\n");
        match &options.stimulus {
            Stimulus::TieOff => out.push_str("    // Your stimulus goes here.\n\n"),
            Stimulus::Random { seed } => {
                random_stimulus(&mut out, module, plan, *seed);
            }
            // Refused before this point; see `generate`.
            Stimulus::Drawn(_) => {}
        }
    }

    if !plan.resets.is_empty() {
        out.push_str("    initial begin\n");
        for reset in &plan.resets {
            let asserted = u8::from(!reset.active_low);
            let _ = writeln!(
                out,
                "        {} = 1'b{asserted};  // active {}{}",
                reset.port,
                if reset.active_low { "low" } else { "high" },
                if reset.asynchronous { ", asynchronous" } else { "" }
            );
        }
        match plan.clocks.first() {
            Some(clock) => {
                let cycles = plan.resets.iter().map(|r| r.cycles).max().unwrap_or(5);
                let _ = writeln!(out, "        repeat ({cycles}) @(posedge {});", clock.port);
            }
            None => out.push_str("        #100;\n"),
        }
        for reset in &plan.resets {
            let released = u8::from(reset.active_low);
            let _ = writeln!(out, "        {} = 1'b{released};", reset.port);
        }
        if driving {
            // Blocking, because this is an `initial` block: `<=` there is a
            // non-blocking assignment every simulator executes as a blocking
            // one anyway, and Verilator warns about the pretence.
            out.push_str(
                "        rtlscope_running = 1'b1;
",
            );
        }
        out.push_str("    end\n\n");
    } else if driving {
        // Nothing resets, so there is nothing to wait for.
        out.push_str("    initial rtlscope_running = 1'b1;\n\n");
    }

    // The design, every port connected by name.
    let _ = writeln!(out, "    {top} #(");
    let overridable: Vec<&rtlscope_ir::Param> =
        module.params.iter().filter(|p| !p.is_local).collect();
    let mut lines = Vec::new();
    for param in &overridable {
        let value = options
            .overrides
            .iter()
            .find(|(name, _)| name == &param.name)
            .map_or(param.value, |(_, value)| *value);
        lines.push(format!("        .{}({value})", param.name));
    }
    if lines.is_empty() {
        // A module with nothing to override still needs valid syntax.
        out.truncate(out.len() - format!("    {top} #(\n").len());
        let _ = writeln!(out, "    {top} u_dut (");
    } else {
        out.push_str(&lines.join(",\n"));
        out.push_str("\n    ) u_dut (\n");
    }

    let connections: Vec<String> =
        module.ports.iter().map(|port| format!("        .{}({})", port.name, port.name)).collect();
    out.push_str(&connections.join(",\n"));
    out.push_str("\n    );\n\n");

    // The dump, and an end.
    let target = match &options.dump_scope {
        Some(scope) => format!("tb_{top}.u_dut.{scope}"),
        None => format!("tb_{top}"),
    };
    out.push_str("    initial begin\n");
    let _ = writeln!(out, "        $dumpfile(\"{top}.fst\");");
    let _ = writeln!(out, "        $dumpvars(0, {target});");
    match plan.clocks.first() {
        Some(clock) => {
            let _ = writeln!(out, "        repeat ({}) @(posedge {});", options.cycles, clock.port);
        }
        None => {
            let _ = writeln!(out, "        #{};", options.cycles * 10);
        }
    }
    out.push_str("        $finish;\n");
    out.push_str("    end\n\nendmodule\n");
    out
}

/// Drives every input that is not a clock or a reset, at random, every cycle.
///
/// This is the difference between a harness that produces an empty waveform and
/// one that produces a pipeline with something in it. `$urandom` is seeded so
/// two runs of the same design give the same dump — a picture that changed
/// every time it was drawn would be no use for comparing anything.
///
/// A vector wider than 32 bits is filled a word at a time, because that is what
/// `$urandom` returns; concatenating whole calls keeps every bit driven rather
/// than leaving the top of a wide bus at zero forever.
fn random_stimulus(out: &mut String, module: &rtlscope_ir::Module, plan: &ClockPlan, seed: u32) {
    let Some(clock) = plan.clocks.first() else {
        out.push_str(
            "    // Nothing clocks this module, so there is no edge to drive inputs on.\n\n",
        );
        return;
    };

    out.push_str(
        "    // Driven at random so that something actually flows through the design.\n\
         \x20   // This knows no protocol: a `ready` that says wait is ignored. It makes a\n\
         \x20   // waveform, not a verdict.\n",
    );
    // Through a variable, not as a literal: Icarus rejects `$urandom(1)`
    // outright — "seed must be an integer/time variable or a register" — and
    // every simulator accepts the variable form.
    let _ = writeln!(out, "    int rtlscope_seed = {seed};");
    out.push_str("    initial void'($urandom(rtlscope_seed));\n");
    let _ = writeln!(out, "    always @(posedge {}) if (rtlscope_running) begin", clock.port);
    for port in &plan.tied_off {
        let width =
            module.ports.iter().find(|p| &p.name == port).map_or(1, |p| module.net(p.net).width);
        let _ = writeln!(out, "        {port} <= {};", urandom(width));
    }
    out.push_str("    end\n\n");
}

/// A random value of exactly this many bits.
fn urandom(width: u32) -> String {
    if width <= 32 {
        return format!("{width}'($urandom)");
    }
    // `$urandom` is 32 bits wide, so a wider port takes several of them.
    let words = width.div_ceil(32);
    let parts: Vec<&str> = std::iter::repeat_n("$urandom", words as usize).collect();
    format!("{width}'({{{}}})", parts.join(", "))
}

fn file_list(options: &TbOptions) -> String {
    let mut out = String::from("// The sources to compile, one per line.\n");
    for source in &options.sources {
        let _ = writeln!(out, "{source}");
    }
    out
}

fn script(top: &str) -> String {
    format!(
        "# Generated by `rtlscope tb-init --flavor sv`.\n\
         #\n\
         # Run this from PowerShell. Icarus started from Git Bash exits 127 with an\n\
         # empty stderr, which reads exactly like success.\n\n\
         iverilog -g2012 -o tb_{top}.vvp -f files.f tb_{top}.sv\n\
         if ($LASTEXITCODE -ne 0) {{ exit $LASTEXITCODE }}\n\
         vvp tb_{top}.vvp -fst\n\
         Write-Host \"waveform: $PWD\\{top}.fst\"\n"
    )
}
